services:

  db:
    image: postgres:15
    container_name: bi_docker_database
    hostname: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bestInsurance
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data

  app-api:
    image: davidabidoye/best-insurance-api:latest
    container_name: bi_docker_api
    restart: always
    ports:
      - 8080:8080
      - 5006:5005
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bestInsurance
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      DATALOADER_LOADSAMPLE: true
      EVENTLISTENER_QUEUE_NAME: subscriptionLogQueue
      EVENTLISTENER_ENABLED: true
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9090
      SPRINGDOC_OAUTHFLOW_AUTHORIZATIONURL: http://localhost:9090/oauth2/authorize
      SPRINGDOC_OAUTHFLOW_TOKENURL: http://localhost:9090/oauth2/token
    depends_on:
      - db
      - oauth-server

  oauth-server:
    image: davidabidoye/best-insurance-oauth2-server:latest
    container_name: bi_docker_auth_server
    hostname: auth-server
    restart: always
    ports:
      - 9090:9090
    environment:
      SPRING_SECURITY_OAUTH2_AUTHORIZATIONSERVER_ISSUER: http://auth-server:9090

  adminer:
    image: adminer
    container_name: bi_docker_adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data:


