services:

  db:
    image: postgres:15
    container_name: bi_docker_database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bestInsurance
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data

  bestInsurance:
    image: davidabidoye/best-insurance-api:latest
    container_name: bi_docker_bestInsurance
    restart: always
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bestInsurance
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: bi_docker_adminer
    restart: always
    ports:
      - 8081:8080

volumes:
    db-data:


